# Vercel Auto-Approval Configuration
# This file defines the criteria for trusted users who can have their Vercel deployments auto-approved

# Explicit trusted users (always approved)
trusted_users:
  - sandeepvashishtha  # Project Lead

# Contribution-based criteria
# Users meeting these criteria will be considered trusted
criteria:
  core_maintainer:
    min_contributions: 100
    min_followers: 50
    auto_approve: true
    
  senior_dev:
    min_contributions: 50
    min_followers: 20
    auto_approve: true
    
  active_contributor:
    min_contributions: 20
    min_followers: 0
    auto_approve: true
    
  regular_contributor:
    min_contributions: 10
    min_followers: 0
    auto_approve: false  # Requires manual approval

# Additional settings
settings:
  # Whether to comment on PRs when auto-approving
  comment_on_approval: true
  
  # Whether to notify when a user becomes trusted
  notify_trusted_status: true
  
  # Environments to auto-approve (Vercel environments)
  auto_approve_environments:
    - "vercel.app"
    - "vercel-preview"
    
  # Maximum number of deployments to auto-approve per PR
  max_auto_approvals_per_pr: 5